pylint:
  image: python:3.8
  script:
    - pip install pylint
    - pip install .
    - pylint src --rcfile=.pylintrc
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  allow_failure: true # only warn about linter errors, no hard enforcement
