# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common.proto
# Protobuf Python Version: 5.28.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    2,
    '',
    'common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\"\x1c\n\x04Vec2\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\"\'\n\x04Vec3\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\"2\n\x04Quat\x12\t\n\x01w\x18\x01 \x01(\x02\x12\t\n\x01x\x18\x02 \x01(\x02\x12\t\n\x01y\x18\x03 \x01(\x02\x12\t\n\x01z\x18\x04 \x01(\x02\"\'\n\x05Model\x12\x1e\n\x08gestures\x18\x01 \x03(\x0e\x32\x0c.GestureType*\x8e\x01\n\x0bGestureType\x12\x08\n\x04NONE\x10\x00\x12\r\n\tPINCH_TAP\x10\x01\x12\n\n\x06\x43LENCH\x10\x02\x12\x0f\n\x0bSURFACE_TAP\x10\x03\x12\x0e\n\nPINCH_HOLD\x10\x04\x12\r\n\tDPAD_LEFT\x10\x05\x12\x0e\n\nDPAD_RIGHT\x10\x06\x12\x0b\n\x07\x44PAD_UP\x10\x07\x12\r\n\tDPAD_DOWN\x10\x08\x42\r\xaa\x02\nPsix.Protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\nPsix.Proto'
  _globals['_GESTURETYPE']._serialized_start=181
  _globals['_GESTURETYPE']._serialized_end=323
  _globals['_VEC2']._serialized_start=16
  _globals['_VEC2']._serialized_end=44
  _globals['_VEC3']._serialized_start=46
  _globals['_VEC3']._serialized_end=85
  _globals['_QUAT']._serialized_start=87
  _globals['_QUAT']._serialized_end=137
  _globals['_MODEL']._serialized_start=139
  _globals['_MODEL']._serialized_end=178
# @@protoc_insertion_point(module_scope)
