# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: watch_output.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import touch_sdk.protobuf.vec_pb2 as vec__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12watch_output.proto\x1a\tvec.proto\"s\n\x0bSensorFrame\x12\x13\n\x04gyro\x18\x01 \x01(\x0b\x32\x05.Vec3\x12\x12\n\x03\x61\x63\x63\x18\x02 \x01(\x0b\x32\x05.Vec3\x12\x13\n\x04grav\x18\x03 \x01(\x0b\x32\x05.Vec3\x12\x13\n\x04quat\x18\x04 \x01(\x0b\x32\x05.Quat\x12\x11\n\tdeltaTime\x18\x05 \x01(\x05\"n\n\x07Gesture\x12\"\n\x04type\x18\x01 \x01(\x0e\x32\x14.Gesture.GestureType\x12\x11\n\tdeltaTime\x18\x02 \x01(\x05\",\n\x0bGestureType\x12\x08\n\x04NONE\x10\x00\x12\x07\n\x03TAP\x10\x01\x12\n\n\x06\x43LENCH\x10\x02\"\xd4\x01\n\nTouchEvent\x12-\n\teventType\x18\x01 \x01(\x0e\x32\x1a.TouchEvent.TouchEventType\x12\x13\n\x0b\x61\x63tionIndex\x18\x02 \x01(\x05\x12\x12\n\npointerIds\x18\x03 \x03(\x05\x12\x15\n\x06\x63oords\x18\x04 \x03(\x0b\x32\x05.Vec2\x12\x11\n\tdeltaTime\x18\x05 \x01(\x05\"D\n\x0eTouchEventType\x12\x08\n\x04NONE\x10\x00\x12\t\n\x05\x42\x45GIN\x10\x01\x12\x07\n\x03\x45ND\x10\x02\x12\x08\n\x04MOVE\x10\x03\x12\n\n\x06\x43\x41NCEL\x10\x04\".\n\x0bRotaryEvent\x12\x0c\n\x04step\x18\x01 \x01(\x05\x12\x11\n\tdeltaTime\x18\x02 \x01(\x05\",\n\x0b\x42uttonEvent\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\tdeltaTime\x18\x02 \x01(\x05\"\xca\x02\n\x06Update\x12\"\n\x0csensorFrames\x18\x01 \x03(\x0b\x32\x0c.SensorFrame\x12\x1a\n\x08gestures\x18\x02 \x03(\x0b\x32\x08.Gesture\x12 \n\x0btouchEvents\x18\x03 \x03(\x0b\x32\x0b.TouchEvent\x12\"\n\x0c\x62uttonEvents\x18\x04 \x03(\x0b\x32\x0c.ButtonEvent\x12\"\n\x0crotaryEvents\x18\x05 \x03(\x0b\x32\x0c.RotaryEvent\x12\x1f\n\x07signals\x18\x06 \x03(\x0e\x32\x0e.Update.Signal\x12\x11\n\tdeltaTime\x18\x07 \x01(\x05\x12\x10\n\x08unixTime\x18\x08 \x01(\x03\"P\n\x06Signal\x12\x08\n\x04NONE\x10\x00\x12\x0e\n\nDISCONNECT\x10\x01\x12\x14\n\x10\x43ONNECT_APPROVED\x10\x02\x12\x16\n\x12\x44\x45SCRIPTION_UPDATE\x10\x03\x42\r\xaa\x02\nPsix.Protob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'watch_output_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\nPsix.Proto'
  _SENSORFRAME._serialized_start=33
  _SENSORFRAME._serialized_end=148
  _GESTURE._serialized_start=150
  _GESTURE._serialized_end=260
  _GESTURE_GESTURETYPE._serialized_start=216
  _GESTURE_GESTURETYPE._serialized_end=260
  _TOUCHEVENT._serialized_start=263
  _TOUCHEVENT._serialized_end=475
  _TOUCHEVENT_TOUCHEVENTTYPE._serialized_start=407
  _TOUCHEVENT_TOUCHEVENTTYPE._serialized_end=475
  _ROTARYEVENT._serialized_start=477
  _ROTARYEVENT._serialized_end=523
  _BUTTONEVENT._serialized_start=525
  _BUTTONEVENT._serialized_end=569
  _UPDATE._serialized_start=572
  _UPDATE._serialized_end=902
  _UPDATE_SIGNAL._serialized_start=822
  _UPDATE_SIGNAL._serialized_end=902
# @@protoc_insertion_point(module_scope)
